services:
  api:
    build: ./api-service
    ports:
      - "5000:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=${API_URL}
    depends_on:
      - api